export const GET_POST = "GET_POST";
export const GET_POSTS = "GET_POSTS";
export const GET_POST_CATEGORY = "GET_POST_CATEGORY";
export const GET_POST_CATEGORIES = "GET_POST_CATEGORIES";

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_CATEGORY = "GET_PRODUCTS_CATEGORY";
export const GET_PRODUCTS_CATEGORIES = "GET_PRODUCTS_CATEGORIES";

export const GET_USERS = "GET_USERS";
